### ISSUE TITLE
☂️ JNIgen transformations and possibly YAML config removal

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/native#1171]
# Note

All of this could be used for `package:jni` itself, as it already contains a lot of hand-written code for `List`, `Map`, `ByteBuffer`, … I plan to add support for exceptions and it's really useful to write transformers for common exception types and have them either in `package:jni` or even another `package:java_library`.

# Use Cases

### Differences between Java and Dart styles

For example, Java naming convention recommends constants to be `SCREAMING_SNAKE_CASE`, while Dart uses `lowerCamelCase`. 

_=> A way to easily change the case._

### Some words are keywords in Dart

For example, the word `in` is a keyword in Dart and cannot be used as an argument name in a method, but it can be in Java. The current behavior is to add `0` to the end of these reserved names. So `in` becomes `in0`. 

_=> A way to specify certain words to rename._

### Some methods and fields are used in `Object`

Like `hashCode` and `toString`. `toString` is also used in Java, however the return type of the method in Java is `JString`. The current behavior is to add `1` to the end of the existing methods. A prettier renaming would be to change `toString` to `toJString` or `toJavaString`.

_=> A way to change method names, this of course needs to take the subclasses into account as well._

### Some names have a different meaning in Dart semantics

In Dart, `Error`s are classes that we normally don't `catch`, in contrast to `Exception`s which we do `catch`. This is largely the same in Java, however the exceptions that are subclasses of `RuntimeException` are more similar to Dart's `Error`s as they're "unchecked exceptions". One might want to rename classes such as `NullPointerException` to `NullPointerError` to better align with Dart semantics.

_=> A way to change class names._

### Some classes have the same names as `dart:core` classes

Even though it's technically possible to either `import dart:core as core`, or `import &lt;generated> as gen`, it's probably easier to have a different name for classes like `Object` and `String` that exist both in Dart and Java. For example, renaming `Object` to `JObject`.

_=> A way to change class names._

### Purely for aesthetics

Self explanatory! 

#### Java supports method overloading, but Dart does not

This means that `int foo()`, `int foo(int a)`, and `int foo(int a, int b)` will turn into `foo`, `foo1`, and `foo2` in Dart. An alternative for this would be to let users rename each `foo` or to write a custom logic with optional parameters.

_=> A way to change method names._

### Dart supports operator overloading, but Java does not

A good example of this is `java.lang.BigInteger`. Since Java doesn't support operator overloading, it has methods like `add`, `multiply`, `divide`, … These methods could be changed to their respective operators in Dart to match the language better. `List`'s `get` and `put` also correlate with operators `[]` and `[]=`.

_=> A way to convert methods to operators._

### Dart has getters and setters, but Java does not

Java is full of `getFoo`s and `setFoo`s. We can change these methods to getters and setters in Dart. We might only want to do this if we have a private `foo` field. Similarly some methods are better suited to be getters in Dart, an obvious example of this is `hashCode()` that can be converted to `hashCode` getter.

_=> A way to convert methods to setters/getters._

### We might not want to include certain classes/methods/fields

So, we need to have an option to exclude elements from the generated bindings. 

_=> A way to exclude elements._

### Ability to add methods/fields to classes

For example, a `toDartString` could be a good method to add to `JString`, which is not already available. Of course, users could use `extension`s but those have their own limitations for example in case of `static` methods or constructors. This can be as simple as the ability to add any user-defined string to any class.

_=> A way to add custom code._

### Argument names are not available in the bytecode

When parsing from the bytecode, the argument names in methods are not available. This means that a method like `int foo(int bar, double baz)` gets turned into `int foo(int i, double d)`.

_=> A way to rename argument names._

### Ability to implement a Dart class

For example we might want `java.util.List` to implement or mixin `ListMixin` as it is already the case for `package:jni`'s `JList`.

_=> A way to add custom code and to modify the class definition._

# Approaches

## Yaml config with regex support

This is the approach already used by `ffigen`. The syntax is something like:

The point here is not to specify an exact syntax for the yaml, but to give you a general idea of how it can exclude and rename.

### Pros

* Relatively easy to do easy things. 
* Declarative.

### Cons

* Impossible to do complicated things, such as checking for some classes' structure or superclass when deciding about renaming. One such example is when trying to change all `(.*)Exception` classes to `$1Error` classes when these classes extend `RuntimeException`. This and many other such examples are simply not possible to do with a yaml config.
* Regex is notoriously difficult to debug.
* It's not obvious in which order the changes happen. Does only one change happen like a switch statement? Or will they happen in a chain from top to bottom? 
* Fully qualified names in Java include periods and dollar signs (for inner classes) like `a.b.Foo$Bar` which need to be escaped since we allow regex: `a\.b\.Foo\$Bar` which makes it ugly (and error-prone) to do simple things.

Overall, I think it's not a good idea to have all of the transformation logic in yaml.

## Passing functions to Dart config object

Another option would be to ditch the yaml configuration for more complex tasks and write Dart code. We already support this for normal use cases, and we can extend it to do transformations as well.

We could consider exposing a `Method` object instead of only the name to access things such as the name of the enclosing class. 

This is better, we wrap the actual internal `Method` into a wrapper (called `Method` again!) with only the useful information and actions to be exposed to the user. This way any changes to the internal representation of `Method` will not break users' config code.

### Pros

* Still easy to do easy things.
* Possible to do more complicated things.

### Cons

* Having a single method for transforming methods, could lead to a messy code with a bunch of branchings.

## Using transformer visitors

This is basically the same as passing functions to Dart config but could be chained together and can suggest better code organization habits.

### Pros

* Almost the same as passing functions, just packaged differently

### Cons

* Could be a bit unfamiliar for users who are not used to the visitor pattern.

# Another Question, is yaml useful?

Suppose we go with the transformer option, will yaml be still useful? It would be weird to start off with yaml, and transfer everything to a Dart config to add a transformer. Another solution would be to "import" a dart file within the Yaml config like

But what do we gain from keeping the yaml around? Is it that much simpler than having a Dart file for beginners? Is JNIgen ever going to be used by beginners?

I would argue that most actual JNIgen use cases are going to be complicated enough to need some form of transformation.

# Things to keep in mind

## Imported bindings

Users cannot modify the imported bindings as they are already generated. This will impose certain limitations on what they can and cannot do. For example, one cannot rename an imported class, so we probably will have two classes `Class` and `MutableClass`, where `Class` is not renamable. Or have an `imported` boolean getter and throw when trying to modify an imported class.

What about fields and methods? The same method could be used in an imported class, and we cannot change its name if we're extending or implementing that class. 

## Reserved Names

Users might want to add certain names to the reserved namespace of a class. These names should not be reused in the subclasses. This happens when a package author adds custom code to introduce useful fields/methods.

## Issues to tackle

- [ ] https://github.com/dart-lang/native/issues/612
- [x] https://github.com/dart-lang/native/issues/614
- [x] https://github.com/dart-lang/native/issues/571
- [x] https://github.com/dart-lang/native/issues/569
- [ ] Remove yaml in favor of dart scripts for binding generation
- [x] https://github.com/dart-lang/native/issues/664
- [x] https://github.com/dart-lang/native/issues/694
- [x] https://github.com/dart-lang/native/issues/703
- [x] https://github.com/dart-lang/native/issues/726
- [x] https://github.com/dart-lang/native/issues/751
- [ ] https://github.com/dart-lang/native/issues/746
- [x] https://github.com/dart-lang/native/issues/787

**Comment by HosseinYousefi** [comment]
The ideal solution must balance four key requirements:

1.  **User Empowerment:** Users must have powerful and flexible control to rename entities, change method signatures (to getters/setters/operators), exclude elements, and add custom code.
2.  **Predictability:** The system's behavior should be easy to understand. Users should not be surprised by the final generated code. The result of their transformations should be respected.
3.  **Stability:** Generated bindings must be stable across runs. Re-running `jnigen` after a Java class is updated (e.g., with new overloaded methods) should not break existing, valid code by arbitrarily changing the names of previously generated entities.
4.  **Correctness:** The final generated Dart code must always be syntactically valid, free of name collisions, and respect Dart's language rules (keywords, etc.).

## Proposed Architectures

We will evaluate three primary models for integrating the user visitor.

### Option A: Pure User-as-Final-Arbiter (Visitor at the End)

In this model, the user has the final say on all naming. The system generates baseline names, and then the user visitor runs to finalize the output. This is a "raw" implementation where the user's transformer code bears the full responsibility for correctness.

**Pipeline:** `... -> renamer -> **userVisitor** -> dartGenerator`

#### Cons

* **High Complexity Burden:** The user's transformer is responsible for all correctness logic: manual conflict resolution, keyword handling, and manually reading/respecting `renaming.json` for stability.
* **Very High Barrier to Entry:** Simple tasks are difficult and error-prone.
* **Difficult Transformer Composition:** Chaining multiple transformers is fragile.

---

### Option B: System-as-Final-Arbiter (Visitor at the Beginning)

In this model, the user provides their *intent* early in the pipeline. The system uses this intent as a high-priority input for its own robust renaming logic, guaranteeing correctness and stability while trying to honor the user's wishes.

**Pipeline:** `... -> **userVisitor** -> renamer -> dartGenerator`

#### Pros

* **Simplicity & Safety:** Users can write simple, focused transformers. The system acts as a safety net, guaranteeing valid output and managing stability automatically. This is the most accessible model.
* **Safe Composition:** The final `renamer` step can safely arbitrate and gracefully resolve conflicts introduced by a chain of transformers.

#### Cons

* **Potential for Surprise:** The system might override a user's desired name to resolve a conflict. While this can be mitigated with warnings, it violates the principle of "what you set is what you get" and can lead to poor, but valid, APIs (e.g., `recordId$1`).
* **Less Absolute Power:** Users cannot implement a completely custom renaming scheme that might conflict with the system's core correctness rules.

---

### Option C: Guided User-as-Final-Arbiter (Visitor at the End with Proactive API)

This model builds on Option A, keeping the user as the final decision-maker, but equips them with powerful, proactive tools built into the transformation API to mitigate the risks.

**Pipeline:** `... -> renamer -> **userVisitor** -> dartGenerator`

**Key Enhancements to the Visitor API:**

* **Proactive Validation:** The `name` setter on a transformation node will **immediately throw an exception** if the proposed name is a reserved keyword or is already in use by another member in the same class. The user gets instant feedback within a `try/catch` block.
* **Transparent Stability Management:** The user-facing nodes will have a read-only `stableName` property, pre-populated from `renaming.json`. This allows the user's code to easily respect or intentionally override stable names.
* **Changelog & Override Tracking:** When a user's code successfully sets a name that overrides a pre-existing `stableName`, this action can be internally flagged to generate a `changelog.md` file, explicitly documenting breaking changes.

#### Pros

* **Maximum Control with Guardrails:** Achieves the predictability of Option A while solving its most critical safety flaws. The user has the final say, but the API helps them avoid common mistakes, forcing them to produce a clean API.
* **Lowers Barrier to Entry:** Compared to Option A, it's far easier to write a correct transformer.
* **Turns Stability into a Feature:** Stability is no longer a manual chore but an explicit, controllable part of the API.

#### Cons

* **Remaining User Responsibility:** While many risks are mitigated, the user is still fundamentally responsible for correctness, especially for conflicts with superclass members.
* **Brittle Transformer Composition:** While the API will detect and prevent a final name collision by throwing an exception, it does not resolve it. This makes chaining transformers fragile: a conflict caused by two independent transformers will fail the build, forcing the user to manually coordinate the logic between them.

## Recommendation

The choice is between **Option B (Safety by Default)** and **Option C (Power with Guardrails)**.

* **Option B** is the simplest and safest path. It guarantees a successful build, making it a good choice if the primary goal is accessibility. However, it does so at the risk of producing a poor API (`recordId$1`), which is a significant flaw for a library generation tool.
* **Option C** is a more advanced, powerful alternative. It provides the ultimate control that expert library authors require. It prioritizes API elegance over automatic build success by failing loudly when a conflict arises, forcing the developer to make a conscious, high-quality decision.

**Recommendation: Pursue Option C: Guided User-as-Final-Arbiter.**

Given that `jnigen` is an expert-level tool for complex interoperability scenarios, the target audience is well-suited to handle the responsibilities of Option C in exchange for its power and transparency. The proactive validation and "fail-on-conflict" approach ensure a higher-quality final API, which is the primary goal of the tool. The benefits of absolute predictability and control, when combined with strong API guardrails, outweigh the "always-succeeds" but potentially "ugly-API" model of Option B.

**Comment by dcharkes** [comment]
> * However, it does so at the risk of producing a poor API (`recordId$1`), which is a significant flaw for a library generation tool.

I wonder if our renamer should be opt-in instead of default. And the end of the pipeline we should have an error if there are any conflicting names.

> * The user-facing nodes will have a read-only `stableName` property, pre-populated from `renaming.json`.

This would be useful both for user-defined transformers as well as for our current renamer. 👍  I like that we put this in the system and not in a transformer.

From a conceptual point of view, I believe our current renamer should not have any special privileges over the user-defined visitors. E.g. I'd want our users to be able to write a similar visitor that postfixes argument types instead of `$123`. So the visitor API should be powerfull enough to do the kind of renames we currently do (e.g. walking the class hierarchy).

Users then chose option C or B by combining our renamer with their own, or only use ours or only use theirs. (The Dart API should take a list of visitors that are run in sequence.) This design makes the visitors composable and lets users decide what to do:

* `... -> our renamer -> dartGenerator` (current behavior)
* `... -> dartGenerator` (might fail due to duplicate names being output) (should this be the new default?) 
* `... -> **userVisitor** -> dartGenerator` (user just wants to have different renaming, error on emitting duplicate names)
* `... -> **userVisitor** -> our renamer -> dartGenerator` (partial user-renaming, rest done by our renamer, lazy-mode) 
* `... -> our renamer -> **userVisitor** -> dartGenerator` (a different lazy mode)

**Comment by dcharkes** [comment]
> We could rename and deprecate. The previously used names (stored in a json file), can still work but be annotated with `@Deprecated`. (Could we also add a quick fix for this?)

If we want to make the system like this pluggable (and possibly implement the stable names in that way), we could support an arbitrary key-value pair on every node. And have:
* `StableNameReaderVisitor` reads the `renaming.json` and populates the `"stableName": "myName$1"` in the extensible key-value map. And we have an extension method together with the visitor that provides the `String get stableName;`
* `OldNamesReaderVisitor` ditto, reads a `json` containing all old names
* `StableNameWriterVisitor` visits all nodes and reads all names that are output, and at the root of the ast writes the `renaming.json`
* `OldNamesWriterVisitor` visit all the nodes and adds the annotations, and at the root of the ast (last node visited) writes the json.

I don't know if that's trying to push it too far, but I believe having some functionality implemented ourselves in visitors would prove out the architecture for a bunch of potential use cases. (Maybe I'm grossly oversimplifying, anything I am missing why this would be hard as a visitor?)

**Comment by HosseinYousefi** [comment]
> I don't know if that's trying to push it too far, but I believe having some functionality implemented ourselves in visitors would prove out the architecture for a bunch of potential use cases. (Maybe I'm grossly oversimplifying, anything I am missing why this would be hard as a visitor?)

There are unique challenges that we don't want to necessarily expose to the user. For example renaming one element means renaming that element in the entirety of the class hierarchy. If the element is imported from a preexisting library, then we simply cannot rename that element anymore – we may decide to create a secondary element with a different name that forwards the call instead. We should make this happen under-the-hood and only expose API that let the user specify the renaming strategy declaratively instead of constantly dealing with renaming implementation.

This might mean refactoring the AST so that instead of method naming information to be unique per `ClassDecl`, we use a shared top-level `MethodNaming` node that will be shared by many Methods, so all methods of the same signature within a class hierarchy will simply change that.

**Comment by HosseinYousefi** [comment]
> Users then chose option C or B by combining our renamer with their own, or only use ours or only use theirs. (The Dart API should take a list of visitors that are run in sequence.) This design makes the visitors composable and lets users decide what to do:

I like this. I don't want to keep gluing pieces over our AST so there will be quite a lot of refactoring involved here but it will be worth it in the long run.

**Comment by HosseinYousefi** [comment]
The other kind of default renamings and transformations can also be packaged up by third-party users (and some in jnigen). For example converting `getFoo` to `get foo` or converting `.new$k(foo, bar)` to `.fromFooAndBar` can be transformers that the user can optionally use.

**Comment by dcharkes** [comment]
> This might mean refactoring the AST so that instead of method naming information to be unique per `ClassDecl`, we use a shared top-level `MethodNaming` node that will be shared by many Methods, so all methods of the same signature within a class hierarchy will simply change that.

Yeah I was thinking something similar. Instead of having the AST, we'd have something more similar to the analyzer element model:

```dart
abstract class Class {
  String get name;

  Iterable<Method> get methods;

  Class? get parentClass;
  Iterable<Class> get subClasses;
}

abstract class Method {
  Class get classNode;

  ConceptualMethod get conceptualMethod;
}

// name TBD
abstract class ConceptualMethod {
  String get name;

  Iterable<Method> get instances;
}
```

If it's more like a graph than a tree, we need to define the visit order a bit more manual though. Maybe we stick with the order that it would have been in the AST. E.g. we don't visit `ConceptualMethod` nodes by default? Though maybe there is a better order to visit things. E.g. visit classes according to the class hierarchy instead of simply by order in the source code.

**Comment by HosseinYousefi** [comment]
# `jnigen` Transformation Pipeline Design

### Stage 1: Configuration & Parsing

The pipeline begins by gathering all necessary inputs.

* **Inputs:**
    * User's `jnigen` configuration file (source paths, output paths, etc.).
    * Java/Kotlin `.class` files.
    * Java `.java` source files.
* **Actions:**
    1.  **Load Config:** Read the user's primary configuration.
    2.  **Parse Source API:** The appropriate backend (ASM for bytecode, Doclet for source) parses the input files.
* **Output:**
    * A raw, unprocessed internal data model (`internal.Classes`).

### Stage 2: Stability & Dependency Loading (`StabilityLoader`)

This stage loads all stability information from the current project and its dependencies to understand the broader ecosystem.

* **Inputs:**
    * The raw internal model from Stage 1.
    * The `jnigen` configuration, which contains a list of dependent packages to check for stability files.
* **Actions:**
    1.  **Load Dependency Stability:** Based on the list of packages in the config, find and parse all `jnigen.lock` files from those direct and transitive dependencies. This data is aggregated into a single "external stability map".
    2.  **Load Local Stability:** Read the `jnigen.lock` file for the *current* project, if one exists from a previous run. This is the "local stability map".
* **Output:**
    * The raw internal model, now annotated with the loaded external and local stability data.

### Stage 3: Linking & Validation (`Linker`)

This stage enriches the internal data model into a coherent graph and validates it against the ecosystem to prevent conflicts. This is the most critical stage for ensuring compatibility.

* **Inputs:**
    * The annotated internal model from Stage 2.
* **Actions:**
    1.  **Build Internal Graph:**
        * Resolve all type references (`java.lang.String` -> `ClassDecl`).
        * Establish the class hierarchy (`superclass` and `interface` links).
        * Create and assign shared state objects (`SharedMethodState`, `SharedPropertyState`) to link overridden members across the entire class hierarchy.
        * Pre-compute member name scopes for each class for fast conflict detection.
    2.  **Apply Stability Information:**
        * Apply names from the "local stability map" to the shared state objects to ensure re-runs are stable.
        * Mark all entities loaded from the "external stability map" as immutable (`isRenamable = false`).
    3.  **Validate Compatibility (Critical Checks):**
        * **Hierarchy Conflict Check:** Fails the build if the user is attempting to generate a class that is a required superclass of an imported dependency.
        * **Name Conflict Check:** Fails the build if a local renaming rule for an overridden method conflicts with the stable name defined in an imported superclass.
* **Output:**
    * A fully connected, validated, and enriched **internal graph**.

### Stage 4: User-Facing Graph Construction (`GraphBuilder`)

This stage translates the internal data model into the rich, ergonomic API that user transformers will interact with.

* **Inputs:**
    * The validated internal graph from Stage 3.
* **Actions:**
    1.  **Build User Model:** Takes the internal graph and constructs the user-facing graph (`Bindings`, `Class`, `Method`, etc.), including all backlinks (like `enclosingClass`) and mutable name scopes.
    2.  **Topological Sort:** As part of the construction, it performs a topological sort on all classes to ensure that any iteration over the classes will always visit superclasses before their descendants.
* **Output:**
    * The rich, user-facing **transformation graph**.

### Stage 5: Transformation (`TransformerRunner`)

This is the "unified transformer pipeline" where all modifications happen. The state management and conflict detection logic is handled directly by the user-facing graph nodes.

* **Inputs:**
    * The user-facing transformation graph.
    * The user's list of custom transformers (or the default list).
* **Actions:**
    1.  **Assemble Pipeline:** Get the list of `Visitor`s to execute. If the user provided a custom list, use that. Otherwise, use a default list (e.g., `[DefaultExcluder(), DefaultRenamer()]`).
    2.  **Execute Pipeline:** Iterate through the list of transformers and execute their `visit` methods on the graph.
* **Output:**
    * The final, **mutated** user-facing graph.

### Stage 6: Stability & Code Generation

The final stage writes the results to disk.

* **Inputs:**
    * The final, mutated user-facing graph.
* **Actions:**
    1.  **Write Stability File (`StabilityWriter`):** Traverses the final graph and generates a new `jnigen.lock` file for the current project, capturing all final names and structural information for the next run in a YAML format.
    2.  **Generate Dart Code (`DartGenerator`):** Traverses the final graph one last time and generates the `.dart` source files.
* **Output:**
    * The final `.dart` files written to the output directory and the updated `jnigen.lock` file.

**Comment by dcharkes** [comment]
`jnigen.lock` -> `jnigen.lock.json` (Prefer using a known format rather than a custom text format.)

Why the order like this in phase 2 and 3? Wouldn't it be more convenient to have `jnigen.lock.json` talk in terms of the linked graph rather than the raw AST? Or is there something I'm missing?

> Topological Sort

Love it!

**Comment by HosseinYousefi** [comment]
> `jnigen.lock` -> `jnigen.lock.json` (Prefer using a known format rather than a custom text format.)

Honestly just changed it to align with `pubspec.lock` for aesthetic reasons (also yaml vs json – pubspec.lock is yaml)

> Why the order like this in phase 2 and 3? Wouldn't it be more convenient to have `jnigen.lock.json` talk in terms of the linked graph rather than the raw AST? Or is there something I'm missing?

That would work for local stability alone but we are using the same file to "import" other bindings, so we still need linking. For example all bindings import the lockfile of `package:jni` to use `java.util.List`, meaning that in the linking phase we substitute the plain `java.util.List` binary name with concrete object imported from an external package, in this case `package:jni`.

**Comment by dcharkes** [comment]
SGTM

> Honestly just changed it to align with `pubspec.lock` for aesthetic reasons (also yaml vs json – pubspec.lock is yaml)

I'm a big fan of YAML, but I've slowly starting to be convinced that if it's not meant to be read or written by humans, then JSON is the better option. Are you envisioning humans reading this during code review to read the locks? Or are the files going to be so big that users will not be bothered to read them?

(JSON encoding/decoding in Dart is much faster than YAML. For example https://github.com/dart-lang/native/pull/2302.)

**Comment by HosseinYousefi** [comment]
> I'm a big fan of YAML, but I've slowly starting to be convinced that if it's not meant to be read or written by humans, then JSON is the better option. Are you envisioning humans reading this during code review to read the locks? Or are the files going to be so big that users will not be bothered to read them?

Yeah I mentioned that json could be better before: https://github.com/dart-lang/native/issues/746#issuecomment-2124422581

Probably the very first time no one bothers checking the lock files as they can be huge. The smaller diffs could be reviewed to check for breaking changes instead of reviewing a convoluted file full of generated bindings.

**Comment by HosseinYousefi** [comment]
I'm exploring validation while renaming. My initial idea was to have `set name` be smart about the naming scope of the parent node and throw if the user wants to incorrectly set two members to be of the same name. This makes swapping names more difficult, so another `renameMembers` method must also be introduced that will not validate and only does the validation at the end of the atomic batch.

If we start with a sound naming scope, `set name` and `renameMembers` operations guarantee that the namingScope can never become unsound.

However, with the `DefaultRenamer` being an optional visitor, the initial state of the naming scope will be unsound (for instance, due to the fact that in Java multiple methods can have the same name).

Another option is to have `set name` just setting the name without validating anything and have a separate validation step at the end. 

Something in between is validating after each visit, for example while in `visitClass`, we can rename all the members of the class but once the visitClass ends, we validate that the namings are correct. This has the benefit of bringing the error closer to its source but the drawback is that we can't decide to do `MyExcluder` before `MyRenamer` as `MyExcluder` doesn't try to fix the namings.

**Comment by dcharkes** [comment]
> Another option is to have `set name` just setting the name without validating anything and have a separate validation step at the end.

I think this is probably fine. The very nature of a visitor is that while visiting you're in a partial state often.

> Something in between is validating after each visit

I'd say it's probably more sensible to validate after each visitor. (But that kind of forces users to run the default renamer before their own, or to make their own renamer rename everything. I was envisioning composition. Maybe we should achieve composition through the default renamer being available as a mixin? But if the user-defined visitor and the default one don't have the same visit order (because the user loops over the members of a class, reverse them and then visits them manually instead of via the visit method) that doesn't work either.

The validators themselves can also be visitors. Then you can check invariants everywhere in the pipeline of multiple visitors as the pipeline author.

**Comment by HosseinYousefi** [comment]
> (But that kind of forces users to run the default renamer before their own

If we want to run the default renamer in all cases first, then the validate on every rename could also work (since we're starting from a sound state and each transition keeps the state sound) which I think provides the best debuggability between the options.

It's actually probably not a bad idea to run the default renamer at first. The user doesn't have to think about including `DefaultRenamer()` when deciding to add a simple transformer to the pipeline. Each setter can validate as you go, and it's not like you're necessarily going to have much conflict as we're renaming very specifically with dollar signs and most users won't want to rename to stuff with dollar signs in the final API.

**Comment by HosseinYousefi** [comment]
I'm thinking about the way "file" as a concept can be a part of the graph. The reason behind this is so the user can add top-level methods to files, add extensions, add exports, add preamble, etc. Also top-level methods' parents are technically files and not classes (in Kotlin). There are some use cases here as well with regards to moving these top-level members from file to file.

A natural place to put this is in between `Bindings` and `Class` so `Bindings -> DartFile -> Class`, but if do this it messes up with our visiting in topological order concept. So I think we shouldn't have an explicit `visitFile`, instead users can add files on `visitStart` and move classes and top-level members at `visitClass`, `visitMethod`, ... If we want to add a specific preamble to all files, it's just a loop on the files of the root `Bindings` object.

I assume the way that usually members are going to be added to the files are from `visitX`, for example from `visitClass` users can use `cls.enclosingFile` to add extra top-level members so lacking `visitFile` isn't going to be problematic.

**Comment by HosseinYousefi** [comment]
In offline discussion, @dcharkes suggested that in general, let's make it clear that a single rename happens on multiple levels instead of having `method.name = 'someOtherName'` automagically rename all methods in the hierarchy and @goderbauer agreed.

My only concern here is that the concept of renaming a single method doesn't make any sense on its own if we want to keep them all in sync (except if we don't – using extensions). So maybe instead we warn users if they're trying to rename a method that has a "supermethod". So the workflow could look something like this:

1. The users sees that some method is named `foo$3` in class `Bar` and wants to rename it to `foobar`.
2. They write a logic like `bindings.findClass('com.example.Bar').findMethod('...').name = 'foobar'`.
3. JNIgen warns that the method you're renaming originated from `com.example.Foo` which is a supertype of `Bar`.
4. The user now chanegs the original logic to `bindings.findClass('com.example.Foo').findMethod('...').name = 'foobar'`

Also to help the user get the logic right the first time, JNIgen can generate informational comments for each member like:

```
// Inherited from `com.example.Foo`.
// Signature: `...`
```

Renaming still acts on all the method "instances" but this way it's easier to reason about it because it only acts down the hierarchy.

**Comment by dcharkes** [comment]
I was thinking the API would look more like:

```dart
bindings.findClass('com.example.Bar').findMethod('...').allInstances.name = 'foobar';
```

The `.allInstances` returns a `List<Method>`, and the `set name(value)` is an extension method on `List<Method>`.

The way to make it discoverable is to add in the doc comment on `String get name` for the individual methods that you should likely rename all related methods together with a small snippet of how to do it.

**Comment by HosseinYousefi** [comment]
> I was thinking the API would look more like:
> 
> bindings.findClass('com.example.Bar').findMethod('...').allInstances.name = 'foobar';
> The `.allInstances` returns a `List<Method>`, and the `set name(value)` is an extension method on `List<Method>`.
> 
> The way to make it discoverable is to add in the doc comment on `String get name` for the individual methods that you should likely rename all related methods together with a small snippet of how to do it.

So an individual member doesn't have a `set name`?

Probably an extension on `List<Method>` is not the thing we want then, we want to have a dedicated class for the `allinstances`. Otherwise someone could do `[method].name = 'something'` and go around the API!

**Comment by dcharkes** [comment]
Yeah, something like a `MethodGroup`, or `MethodPrototype` that you can describe on that it is all methods everywhere in the hierarchy that are related to each other through overrides and implements clauses.

**Comment by HosseinYousefi** [comment]
But then both of these classes are basically doing the same thing. So we can either just document that a class doesn't have individual methods but it just has method prototypes and keep the same `Method` class.

Or change the way we do renaming to make it more obvious, e.g. instead of `set name`  use `renameInAllInstances(String)`.

**Comment by dcharkes** [comment]
> Or change the way we do renaming to make it more obvious, e.g. instead of `set name` use `renameInAllInstances(String)`.

I was thinking that you might want to do various versions of `.allInstances` that give different groups. E.g. for renaming you want to follow all overrides up and down and all implements transitively. But maybe if you want to add nullability on a library that's not there you only want to do it down. So we decouple the "getting a group" and the "setting of something".

**Comment by HosseinYousefi** [comment]
> I was thinking that you might want to do various versions of `.allInstances` that give different groups. E.g. for renaming you want to follow all overrides up and down and all implements transitively. But maybe if you want to add nullability on a library that's not there you only want to do it down. So we decouple the "getting a group" and the "setting of something".

Good point, so this kinda means that we also have `MethodParameterGroup`s. Tightening the nullability of one should tighten the nullability of everything under it.

I think all this makes the transformer stuff too complicated for my liking though. Something about just setting `.name` and JNIgen handling it everywhere in the hierarchy appeals to me for most use cases. It's very likely that the new name suggested by the user doesn't really conflict with anything anyways.

Likewise for the method parameters, I'd rather handle the nullability sync automatically (as you say, it should only go downwards).

**Comment by dcharkes** [comment]
Those "getting a group" various things should also make it trivial to write validators:

```dart
final group = oneMethod.allInstances(implemented: true, implements: true, overridden: true, overrides: true, transitive: true);
final distinctNames = group.instances.map((e) => e.name).distinct();
if (distinctNames.length > 1) {
  //print warning
}
```

Yeah maybe the setter on the individual parameter and method instances should simply do `void set name(value) => allInstances(with right params).name = value;` then we can have the default case be covered and it's very easy for users to see how to get different behavior by simply looking at the setter implementation.

**Comment by HosseinYousefi** [comment]
> So we decouple the "getting a group" and the "setting of something".

Another point is getting the "only down" group and then setting `.name` is wrong. So by splitting this into two phases we introduced an incorrect combination of phases which wouldn't exist if we had `.renameInAllInstances` and `.changeNullabilityOfAllSubMembers`

**Comment by HosseinYousefi** [comment]
An important scenario to test is running the generator -> removing a method named `foo` and regen -> adding another method named `foo` and regen.

In this case the second `foo` must be named differently that the first `foo`, even though the first `foo` has been completely removed from the bindings. This means that our exporter logic should not only look at the existing member and their stable names but also the previous members that are non-existing but are available in the symbols file and keep them available in the next iterations.

Another argument is that removing `foo` is already a breaking change so it doesn't matter that another `foo` with the same name is taking over its place so it's not necessary to keep a stable name after removing a member.

**Comment by HosseinYousefi** [comment]
We use the fact that this member has been renamed or not quite a lot in the naming conflict resolution algorithms. We have three API options:

* Make the `member.name` getter nullable. If `member.name` is `null`, this member has not been renamed (or even named) yet.
* `member.name` is nullable but defaults to `stableName`. This moves the logic of "if the stable name is available for this member, then use that" from the transformer layer into the graph builder or importer layer. We could do this if we think our users always want to have this logic anyways.
* `member.name` is not nullable but defaults to `stableName ?? originalName` or `originalName`. Users have to manually keep track of which method prototypes have been renamed. It's important to note that `member.name == originalName` does not tell us if the method name has been decided or not. It could be that we decided to keep the original method name which we expect to do most of the times.

I think I want to go with the second option. Having the `name` getter be nullable actually further discourages users to use `member.name` in their APIs which is ideal since they should really be using `.identifier` or `.originalName` getters instead.

**Comment by HosseinYousefi** [comment]
Another possible scenario is that a method can be provided in an implementer of an interface by extending another class. For example:

```java
public class Player {
  // lower your head!
  public void duck() {...}
}

public interface Ducking {
  void duck();
}

public class DuckingPlayer extends Player implements Ducking {
  // No need for anything, implementing Ducking is already satisfied by extending the class Player.
}

public class DuckOwningPlayer extends Player {
  public Duck duck;
} 
```

This means that in the bindings the name of the `duck` method in `Player` and the name of the `duck` method in the `Ducking` interface must be the same, since they're shared as one in the `DuckingPlayer`. This is different than the concept of `MethodPrototype`s. These two methods are technically not each other's super-methods at all (although they of course share the same signature and original name) but since somewhere in the hierarchy, one is used to implement the other, their states must be shared everywhere in the tree.

This can connect multiple unrelated imethods together if they are all implemented or extended in the same class and they share the same method name+signature.

**Comment by HosseinYousefi** [comment]
Another point that came up in #2453 is instead of using symbols.json or similar, let's use annotations on the actual generated bindings and use Dart analyzer to extract stability and symbol information from the source. This way we can see all of the other potential members added by the user and there is only a single source of truth—the Dart source.
