### ISSUE TITLE
☂️ Support Kotlin Features

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/native#615]
Now that we're parsing Kotlin's metadata, we could start adding more and more specific support for Kotlin features. This is an umbrella issue for all these features. Feel free to add more.

- [ ] Inline classes
- [ ] dart-lang/jnigen#188 
- [ ] dart-lang/native#608
- [ ] dart-lang/jnigen#302
- [ ] Generate null-aware types from Kotlin
- [ ] Operator overloading
- [ ] dart-lang/native#598

**Comment by HosseinYousefi** [comment]
Most used Kotlin features are done for the common usecases. Moving the rest to Q3 to focus more on the devX improvements.
